---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: plugins/docker

  - name: gate
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - export GITIGNORE="Dockerfile"
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep "$GITIGNORE" || exit 78
      - git diff --name-only HEAD~1..HEAD | grep "$GITIGNORE" || exit 78

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/goshopify
      auto_tag: true
    when:
      branch:
        - master
